language: node_js

node_js:
  - 12.13.0

after_script:
  - npm run coveralls

notifications:
  slack:
    secure: WKR4bW+cQcLl9TAvZVCg8qfu3nZ3WKOoOBzRkSjQMZBEHp9N8UE2LwQJYJZKKYfg8vocPFXanx1wW9qCUhdYdi6llwXrTInyz/FmZEjhfapRl6xS6WzyEdzLJgPHHRqZiwojopRBlx4m3+DjuNL4Qzqze64osqO0m46xyI6nh/fBlVjaA9J2HostVgj9o9k5itna5HhlEkCrPFUvP8fNfiLbTVLvVWvVjKt66YXzwMIbjF5t0QMqcisUnz7FzMethDaD9SEerWGyG3xi0Y++WbIzFxGtdhC69V1sDem6hy1mdAArK+NobQjtWJ+ECE3H6xRr7Gpyr+fpzRgIv6GdMJ053g93wPoi2RU6h66hQ09suRxScOA1t/Aq0zRcXm187TRHiUnaGU7Y9xEq55zE46hr5CBHy3wWHgyMJjDwpDjqJPkPHY8UEVE8Xhe7OSYgULR/4QB9n/gWEyzzyP5Nx1RndN05cD+W2S8sdJzhP0oskAANAVhr/XjhZDYXrxeptmSOMv2o7NtLVkslEeGOQbrdHG1FlnKn0b8ZDQo0ZXMiwgorKFOLhdgEblh8pXOpyofWUNELX1cG8kwG6RtZtsJoUrXTOcr8mqZSgOgd8IIsqd4U7fXQKsub8aizGO9qNaJwea4mtvS6L9exexRMTq0C9ODMKARITqOJUMzjR5A=
